import * as fs from 'node:fs';

interface Vec3 {
  x: number;
  y: number;
  z: number;
}

interface Triangle {
  normal: Vec3;
  v1: Vec3;
  v2: Vec3;
  v3: Vec3;
  attributeByteCount: number;
}

function cross(a: Vec3, b: Vec3): Vec3 {
  return {
    x: a.y * b.z - a.z * b.y,
    y: a.z * b.x - a.x * b.z,
    z: a.x * b.y - a.y * b.x,
  };
}

function sub(a: Vec3, b: Vec3): Vec3 {
  return { x: a.x - b.x, y: a.y - b.y, z: a.z - b.z };
}

function normalize(v: Vec3): Vec3 {
  const len = Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
  if (len === 0) return { x: 0, y: 0, z: 0 };
  return { x: v.x / len, y: v.y / len, z: v.z / len };
}

export function computeNormal(v1: Vec3, v2: Vec3, v3: Vec3): Vec3 {
  return normalize(cross(sub(v2, v1), sub(v3, v1)));
}

export function writeSTLBinary(triangles: Triangle[]): Buffer {
  // STL binary format: 80 byte header + 4 byte triangle count + 50 bytes per triangle
  const headerSize = 80;
  const countSize = 4;
  const triangleSize = 50; // 12 floats (3 normal + 9 vertex) * 4 bytes + 2 byte attribute
  const totalSize = headerSize + countSize + triangles.length * triangleSize;

  const buffer = Buffer.alloc(totalSize);
  let offset = 0;

  // Header (80 bytes, can be anything)
  buffer.write('Binary STL generated by uniq', offset, 'ascii');
  offset += headerSize;

  // Triangle count
  buffer.writeUInt32LE(triangles.length, offset);
  offset += countSize;

  for (const tri of triangles) {
    // Normal
    buffer.writeFloatLE(tri.normal.x, offset); offset += 4;
    buffer.writeFloatLE(tri.normal.y, offset); offset += 4;
    buffer.writeFloatLE(tri.normal.z, offset); offset += 4;
    // Vertex 1
    buffer.writeFloatLE(tri.v1.x, offset); offset += 4;
    buffer.writeFloatLE(tri.v1.y, offset); offset += 4;
    buffer.writeFloatLE(tri.v1.z, offset); offset += 4;
    // Vertex 2
    buffer.writeFloatLE(tri.v2.x, offset); offset += 4;
    buffer.writeFloatLE(tri.v2.y, offset); offset += 4;
    buffer.writeFloatLE(tri.v2.z, offset); offset += 4;
    // Vertex 3
    buffer.writeFloatLE(tri.v3.x, offset); offset += 4;
    buffer.writeFloatLE(tri.v3.y, offset); offset += 4;
    buffer.writeFloatLE(tri.v3.z, offset); offset += 4;
    // Attribute byte count
    buffer.writeUInt16LE(tri.attributeByteCount, offset); offset += 2;
  }

  return buffer;
}

export function saveSTL(triangles: Triangle[], filePath: string): void {
  const buffer = writeSTLBinary(triangles);
  fs.writeFileSync(filePath, buffer);
}

export function makeTriangle(v1: Vec3, v2: Vec3, v3: Vec3): Triangle {
  const normal = computeNormal(v1, v2, v3);
  return { normal, v1, v2, v3, attributeByteCount: 0 };
}

export function makeQuad(
  v1: Vec3, v2: Vec3, v3: Vec3, v4: Vec3,
): Triangle[] {
  return [
    makeTriangle(v1, v2, v3),
    makeTriangle(v1, v3, v4),
  ];
}

export type { Vec3, Triangle };
